runtime! debian.vim

if has("syntax")
  syntax on
endif

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("autocmd")
  filetype plugin indent on
endif


set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set hlsearch        " Resaltar la búsqueda
set incsearch		" Incremental search
set mouse=a		    " Enable mouse usage (all modes)
set number          " Mostrar los números de línea
set textwidth=80    " Fijar ancho de línea en 80 caracteres
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab

"set showcmd		" Show (partial) command in status line.
"set smartcase		" Do smart case matching
"set autowrite		" Automatically save before commands like :next and :make
"set hidden         " Hide buffers when they are abandoned

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
