runtime! debian.vim

if has("syntax")
  syntax on
endif

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("autocmd")
  filetype plugin indent on
endif


set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set hlsearch        " Hilight search
set incsearch		    " Incremental search
set mouse=a		      " Enable mouse usage (all modes)
set number          " Show line numbers
set textwidth=80    " Set line width to 80 characters
set softtabstop=4   "Set soft tabstop to the size 4
set shiftwidth=4    
set tabstop=4
set expandtab

"set showcmd		" Show (partial) command in status line.
"set smartcase		" Do smart case matching
"set autowrite		" Automatically save before commands like :next and :make
"set hidden         " Hide buffers when they are abandoned

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
